services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: server
    ports:
      - "3103:80"
    restart: always
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    container_name: app
    environment:
      - HASHCDSTORAGE=/storage
      - HASHCD_CACHE_SIZE=512
      - HASHCD_CACHE_ITEM_SIZE=10
    volumes:
      - storage:/storage
    restart: always
volumes:
  storage: